<template><div class="profile-page"><div class="section-content"><h2>账户设置</h2><el-tabs v-if="auth.isLoggedIn"><el-tab-pane label="修改密码"><el-form :model="pwForm" ref="pwRef" label-width="100px" style="max-width:400px"><el-form-item label="原密码" prop="old"><el-input v-model="pwForm.old" type="password" show-password/></el-form-item><el-form-item label="新密码" prop="newPw"><el-input v-model="pwForm.newPw" type="password" show-password/><div style="font-size:12px;color:#999;margin-top:4px">≥8位，含大小写+数字+特殊字符</div></el-form-item><el-form-item><el-button type="primary" @click="changePw" :loading="pwLoading">修改密码</el-button></el-form-item></el-form></el-tab-pane><el-tab-pane label="基本信息"><el-form :model="infoForm" label-width="80px" style="max-width:400px"><el-form-item label="用户名"><el-input :model-value="auth.user?.username" disabled/></el-form-item><el-form-item label="昵称"><el-input v-model="infoForm.nickname"/></el-form-item><el-form-item label="手机号"><el-input v-model="infoForm.phone"/></el-form-item><el-form-item><el-button type="primary" @click="saveInfo" :loading="infoLoading">保存</el-button></el-form-item></el-form></el-tab-pane></el-tabs><el-empty v-else description="请先登录"><el-button type="primary" @click="$router.push('/login')">去登录</el-button></el-empty></div></div></template>
<script setup>
import {ref,reactive} from 'vue';import axios from 'axios';import {ElMessage} from 'element-plus';import {useAuthStore} from '../../stores/auth'
const auth=useAuthStore();auth.restoreSession()
const pwForm=reactive({old:'',newPw:''});const pwLoading=ref(false)
const infoForm=reactive({nickname:auth.user?.nickname||'',phone:''});const infoLoading=ref(false)
async function changePw(){if(!pwForm.old||!pwForm.newPw){ElMessage.warning('请填写完整');return};pwLoading.value=true;try{await axios.put('/api/user/updatePassword',{oldPassword:pwForm.old,newPassword:pwForm.newPw});ElMessage.success('密码修改成功');pwForm.old='';pwForm.newPw=''}catch(e){ElMessage.error(e.response?.data?.message||'修改失败')}finally{pwLoading.value=false}}
async function saveInfo(){infoLoading.value=true;try{await axios.put('/api/user/updateInfo',{nickname:infoForm.nickname,phone:infoForm.phone});ElMessage.success('保存成功')}catch{ElMessage.error('保存失败')}finally{infoLoading.value=false}}
</script>
<style scoped>.profile-page{min-height:70vh;background:#f5f6f7;padding-bottom:40px}.section-content{max-width:600px;margin:0 auto;padding:20px}h2{padding:10px 0}</style>
